name: Upload Latest Artifacts to Release

on:
  release:
    types: [edited]

jobs:
  package:
    name: Release New Desktop App
    runs-on: ubuntu-latest
    steps:
      - name: Download latest artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          branch: master
      - name: Flatten Directory structure
        run: |
          find ./ -mindepth 2 -type f -exec mv -t ./ -i '{}' +
          find . -type d -empty -delete
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
